name: api_services
description: Easy to use http services
version: 1.0.0
repository: https://github.com/mohammadAtaullahBD/api_services_package.git

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
